export const DO_GET_USERS_REQUEST = "DO_GET_USERS_REQUEST";
export const DO_GET_USERS_IN_PROGRESS = "DO_GET_USERS_IN_PROGRESS";
export const DO_GET_USERS_SUCCESS = "DO_GET_USERS_SUCCESS";
export const DO_GET_USERS_FAILED = "DO_GET_USERS_FAILED";

export const DO_DELETE_USER_REQUEST = "DO_DELETE_USER_REQUEST";
export const DO_DELETE_USER_IN_PROGRESS = "DO_DELETE_USER_IN_PROGRESS";
export const DO_DELETE_USER_SUCCESS = "DO_DELETE_USER_SUCCESS";
export const DO_DELETE_USER_FAILED = "DO_DELETE_USER_FAILED";

export const DO_ADD_USER_REQUEST = "DO_ADD_USER_REQUEST";
export const DO_ADD_USER_IN_PROGRESS = "DO_ADD_USER_IN_PROGRESS";
export const DO_ADD_USER_SUCCESS = "DO_ADD_USER_SUCCESS";
export const DO_ADD_USER_FAILED = "DO_ADD_USER_FAILED";
