export const DO_LOGIN_REQUEST = "DO_LOGIN_REQUEST";
export const DO_LOGIN_IN_PROGRESS = "DO_LOGIN_IN_PROGRESS";
export const DO_LOGIN_SUCCESS = "DO_LOGIN_SUCCESS";
export const DO_LOGIN_FAILED = "DO_LOGIN_FAILED";

export const DO_REGISTER_REQUEST = "DO_REGISTER_REQUEST";
export const DO_REGISTER_IN_PROGRESS = "DO_REGISTER_IN_PROGRESS";
export const DO_REGISTER_SUCCESS = "DO_REGISTER_SUCCESS";
export const DO_REGISTER_FAILED = "DO_REGISTER_FAILED";

export const DO_FORGOT_PASSWORD_REQUEST = "DO_FORGOT_PASSWORD_REQUEST";
export const DO_FORGOT_PASSWORD_IN_PROGRESS = "DO_FORGOT_PASSWORD_IN_PROGRESS";
export const DO_FORGOT_PASSWORD_SUCCESS = "DO_FORGOT_PASSWORD_SUCCESS";
export const DO_FORGOT_PASSWORD_FAILED = "DO_FORGOT_PASSWORD_FAILED";

export const DO_RESET_PASSWORD_REQUEST = "DO_RESET_PASSWORD_REQUEST";
export const DO_RESET_PASSWORD_IN_PROGRESS = "DO_RESET_PASSWORD_IN_PROGRESS";
export const DO_RESET_PASSWORD_SUCCESS = "DO_RESET_PASSWORD_SUCCESS";
export const DO_RESET_PASSWORD_FAILED = "DO_RESET_PASSWORD_FAILED";
